version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apk update && apk add git && apk add rsync
      - checkout

deployment:
  prod:
    branch: master
    commands:
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - sudo ssh pcutler@nflpool.xyz rsync -avz ./public $DIGITALOCEAN_IP:/srv/paulcutler.og/test_html/
