version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apk update && apk add git && apk add rsync
      - checkout
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: ssh-keyscan -H nflpool.xyz >> ~/.ssh/known_hosts
      - run: rsync -avz $HUGO_BUILD_DIR pcutler@nflpool.xyz:/srv/paulcutler.org/test_html/


