version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apk update && apk add git && apk add rsync
      - checkout
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: sudo ssh pcutler@nflpool.xyz rsync -avz ./public nflpool.xyz:/srv/paulcutler.og/test_html/

